# Generated by Django 6.0.2 on 2026-03-01 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessingReqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(default='FITS', max_length=50)),
                ('file_quality', models.CharField(default='High', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExposureSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_time', models.FloatField()),
                ('num_exposures', models.IntegerField()),
                ('total_time', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SciencePlan',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('astronomer_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Clarification Requested', 'Clarification Requested'), ('Revised', 'Revised'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('submission_notes', models.TextField(blank=True, null=True)),
                ('rejection_category', models.CharField(blank=True, choices=[('Technical Infeasibility', 'Technical Infeasibility'), ('Scientific Merit Issues', 'Scientific Merit Issues'), ('Scheduling Conflict', 'Scheduling Conflict'), ('Incomplete Information', 'Incomplete Information'), ('Observing Conditions Unrealistic', 'Observing Conditions Unrealistic'), ('Data Specification Issues', 'Data Specification Issues'), ('Instrument Configuration Problem', 'Instrument Configuration Problem'), ('Other', 'Other')], max_length=100, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('exposure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='plans.exposuresettings')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProcessingSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_mode', models.CharField(default='B&W', max_length=50)),
                ('contrast', models.IntegerField(default=50)),
                ('brightness', models.IntegerField(default=50)),
                ('saturation', models.IntegerField(default=50)),
                ('data_proc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_proc', to='plans.dataprocessingreqs')),
            ],
        ),
        migrations.CreateModel(
            name='ObservingConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeing', models.FloatField()),
                ('cloud_cover', models.IntegerField()),
                ('water_vapor', models.IntegerField()),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='plans.scienceplan')),
            ],
        ),
        migrations.AddField(
            model_name='exposuresettings',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exposure', to='plans.scienceplan'),
        ),
        migrations.AddField(
            model_name='dataprocessingreqs',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_proc', to='plans.scienceplan'),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ra', models.CharField(max_length=50)),
                ('dec', models.CharField(max_length=50)),
                ('magnitude', models.FloatField()),
                ('object_type', models.CharField(max_length=100)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='plans.scienceplan')),
            ],
        ),
    ]
